average = int(input("SCORE : "))
command = int(input("transmutation: 20/30/40/50/60/70/80/90/100 : "))


if command == 20:
    if average == 1:
        print(f'{average} result = 4.8')
    elif average == 2:
        print(f'{average} result = 4.7')
    elif average == 3:
        print(f'{average} result = 4.6')
    elif average == 4:
        print(f'{average} result = 4.5')
    elif average == 5:
        print(f'{average} result = 4.4')
    elif average == 6:
        print(f'{average} result = 4.2')
    elif average == 7:
        print(f'{average} result = 4.0')
    elif average == 8:
        print(f'{average} result = 3.8')
    elif average == 9:
        print(f'{average} result = 3.6')
    elif average == 10:
        print(f'{average} result = 3.4')
    elif average == 11:
        print(f'{average} result = 3.2')
    elif average == 12:
        print(f'{average} result = 3.0')
    elif average == 13:
        print(f'{average} result = 2.7')
    elif average == 14:
        print(f'{average} result = 2.5')
    elif average == 15:
        print(f'{average} result = 2.3')
    elif average == 16:
        print(f'{average} result = 2.1')
    elif average == 17:
        print(f'{average} result = 1.9')
    elif average == 18:
        print(f'{average} result = 1.7')
    elif average == 19:
        print(f'{average} result = 1.4')
    elif average == 20:
        print(f'{average} result = 1.0')
if command == 30:
    if average == 1:
        print(f'{average} result = 4.8')
    elif average == 2:
        print(f'{average} result = 4.7')
    elif average == 3:
        print(f'{average} result = 4.6')
    elif average == 4:
        print(f'{average} result = 4.5')
    elif average == 5:
        print(f'{average} result = 4.4')
    elif average == 6:
        print(f'{average} result = 4.3')
    elif average == 7:
        print(f'{average} result = 4.2')
    elif average == 8:
        print(f'{average} result = 4.1')
    elif average == 9:
        print(f'{average} result = 4.0')
    elif average == 10:
        print(f'{average} result = 3.9')
    elif average == 11:
        print(f'{average} result = 3.8')
    elif average == 12:
        print(f'{average} result = 3.7')
    elif average == 13:
        print(f'{average} result = 3.6')
    elif average == 14:
        print(f'{average} result = 3.5')
    elif average == 15:
        print(f'{average} result = 3.4')
    elif average == 16:
        print(f'{average} result = 3.3')
    elif average == 17:
        print(f'{average} result = 3.2')
    elif average == 18:
        print(f'{average} result = 3.1')
    elif average == 19:
        print(f'{average} result = 3.0')
    elif average == 20:
        print(f'{average} result = 2.9')
    elif average == 21:
        print(f'{average} result = 2.8')
    elif average == 22:
        print(f'{average} result = 2.6')
    elif average == 23:
        print(f'{average} result = 2.4')
    elif average == 24:
        print(f'{average} result = 2.2')
    elif average == 25:
        print(f'{average} result = 2.0')
    elif average == 26:
        print(f'{average} result = 1.8')
    elif average == 27:
        print(f'{average} result = 1.6')
    elif average == 28:
        print(f'{average} result = 1.4')
    elif average == 29:
        print(f'{average} result = 1.2')
    elif average == 30:
        print(f'{average} result = 1.0')
if command == 40:
    if average == 1:
        print(f'{average} result = 4.9')
    elif average == 2 or average == 3:
        print(f'{average} result = 4.8')
    elif average == 4 or average == 5:
        print(f'{average} result = 4.7')
    elif average == 6 or average == 7:
        print(f'{average} result = 4.6')
    elif average == 8 or average == 9:
        print(f'score {average} result = 4.5')
    elif average == 10:
        print(f'{average} result = 4.4')
    elif average == 11:
        print(f'{average} result = 4.3')
    elif average == 12:
        print(f'{average} result = 4.2')
    elif average == 13:
        print(f'{average} result = 4.1')
    elif average == 14:
        print(f'{average} result = 4.0')
    elif average == 15:
        print(f'{average} result = 3.9')
    elif average == 16:
        print(f'{average} result = 3.8')
    elif average == 17:
        print(f'{average} result = 3.7')
    elif average == 18:
        print(f'{average} result = 3.6')
    elif average == 19:
        print(f'{average} result = 3.5')
    elif average == 20:
        print(f'{average} result = 3.4')
    elif average == 21:
        print(f'{average} result = 3.3')
    elif average == 22:
        print(f'{average} result = 3.2')
    elif average == 23:
        print(f'{average} result = 3.1')
    elif average == 24:
        print(f'{average} result = 3.0')
    elif average == 25:
        print(f'{average} result = 2.8')
    elif average == 26:
        print(f'{average} result = 2.7')
    elif average == 27:
        print(f'{average} result = 2.6')
    elif average == 28:
        print(f'{average} result = 2.5')
    elif average == 29:
        print(f'{average} result = 2.4')
    elif average == 30:
        print(f'{average} result = 2.3')
    elif average == 31:
        print(f'{average} result = 2.2')
    elif average == 32:
        print(f'{average} result = 2.1')
    elif average == 33:
        print(f'{average} result = 2.0')
    elif average == 34:
        print(f'{average} result = 1.9')
    elif average == 35:
        print(f'{average} result = 1.8')
    elif average == 36:
        print(f'{average} result = 1.7')
    elif average == 37:
        print(f'{average} result = 1.6')
    elif average == 38:
        print(f'{average} result = 1.4')
    elif average == 39:
        print(f'{average} result = 1.2')
    elif average == 40:
        print(f'{average} result = 1.0')
if command == 50:
    if average == 1:
        print(f'{average} result = 4.9 ')
    elif average == 2 or average == 3:
        print(f'{average} result = 4.8 ')
    elif average == 4 or average == 5:
        print(f'{average} result = 4.7 ')
    elif average == 6 or average == 7:
        print(f'{average} result = 4.6 ')
    elif average == 8 or average == 9:
        print(f'{average} result = 4.5 ')
    elif average == 10 or average == 11:
        print(f'{average} result = 4.4 ')
    elif average == 12 or average == 13:
        print(f'{average} result = 4.3 ')
    elif average == 14 or average == 15:
        print(f'{average} result = 4.2 ')
    elif average == 16 or average == 17:
        print(f'{average} result = 4.1 ')
    elif average == 18 or average == 19:
        print(f'{average} result = 4.0 ')
    elif average == 20 or average == 21:
        print(f'{average} result = 3.9 ')
    elif average == 22:
        print(f'{average} result = 3.8')
    elif average == 23:
        print(f'{average} result = 3.7')
    elif average == 24:
        print(f'{average} result = 3.6')
    elif average == 25:
        print(f'{average} result = 3.5')
    elif average == 26:
        print(f'{average} result = 3.4')
    elif average == 27:
        print(f'{average} result = 3.3')
    elif average == 28:
        print(f'{average} result = 3.2')
    elif average == 29:
        print(f'{average} result = 3.1')
    elif average == 30:
        print(f'{average} result = 3.0')
    elif average == 31:
        print(f'{average} result = 2.9')
    elif average == 32:
        print(f'{average} result = 2.8')
    elif average == 33:
        print(f'{average} result = 2.7')
    elif average == 34:
        print(f'{average} result = 2.6')
    elif average == 35:
        print(f'{average} result = 2.5')
    elif average == 36:
        print(f'{average} result = 2.4')
    elif average == 37:
        print(f'{average} result = 2.3')
    elif average == 38:
        print(f'{average} result = 2.2')
    elif average == 39:
        print(f'{average} result = 2.1')
    elif average == 40:
        print(f'{average} result = 2.0')
    elif average == 41:
        print(f'{average} result = 1.9')
    elif average == 42:
        print(f'{average} result = 1.8')
    elif average == 43:
        print(f'{average} result = 1.7')
    elif average == 44:
        print(f'{average} result = 1.6')
    elif average == 45:
        print(f'{average} result = 1.5')
    elif average == 46:
        print(f'{average} result = 1.4')
    elif average == 47:
        print(f'{average} result = 1.3')
    elif average == 48:
        print(f'{average} result = 1.2')
    elif average == 49:
        print(f'{average} result = 1.1')
    elif average == 50:
        print(f'{average} result = 1.0')
if command == 60:
    if average == 1:
        print(f'{average} result = 4.9 ')
    elif average == 2 or average == 3:
        print(f'{average} result = 4.8 ')
    elif average == 4 or average == 5:
        print(f'{average} result = 4.7 ')
    elif average == 6 or average == 7:
        print(f'{average} result = 4.6 ')
    elif average == 8 or average == 9:
        print(f'{average} result = 4.5 ')
    elif average == 10 or average == 11:
        print(f'{average} result = 4.4 ')
    elif average == 12 or average == 13:
        print(f'{average} result = 4.3 ')
    elif average == 14 or average == 15:
        print(f'{average} result = 4.2 ')
    elif average == 16 or average == 17:
        print(f'{average} result = 4.1 ')
    elif average == 18 or average == 19:
        print(f'{average} result = 4.0 ')
    elif average == 20 or average == 21:
        print(f'{average} result = 3.9 ')
    elif average == 22 or average == 23:
        print(f'{average} result = 3.8')
    elif average == 24 or average == 25:
        print(f'{average} result = 3.7')
    elif average == 26 or average == 27:
        print(f'{average} result = 3.6')
    elif average == 28 or average == 29:
        print(f'{average} result = 3.5')
    elif average == 30 or average == 31:
        print(f'{average} result = 3.4')
    elif average == 32 or average == 33:
        print(f'{average} result = 3.3')
    elif average == 34:
        print(f'{average} result = 3.2')
    elif average == 35:
        print(f'{average} result = 3.1')
    elif average == 36:
        print(f'{average} result = 3.0')
    elif average == 37:
        print(f'{average} result = 2.9')
    elif average == 38:
        print(f'{average} result = 2.8')
    elif average == 39:
        print(f'{average} result = 2.7')
    elif average == 40:
        print(f'{average} result = 2.6')
    elif average == 41:
        print(f'{average} result = 2.5')
    elif average == 42 or average == 43:
        print(f'{average} result = 2.4')
    elif average == 44 or average == 45:
        print(f'{average} result = 2.3')
    elif average == 46 or average == 47:
        print(f'{average} result = 2.2')
    elif average == 48 or average == 49:
        print(f'{average} result = 2.1')
    elif average == 50:
        print(f'{average} result = 2.0')
    elif average == 51:
        print(f'{average} result = 1.9')
    elif average == 52:
        print(f'{average} result = 1.8')
    elif average == 53:
        print(f'{average} result = 1.7')
    elif average == 54:
        print(f'{average} result = 1.6')
    elif average == 55:
        print(f'{average} result = 1.5')
    elif average == 56:
        print(f'{average} result = 1.4')
    elif average == 57:
        print(f'{average} result = 1.3')
    elif average == 58:
        print(f'{average} result = 1.2')
    elif average == 59:
        print(f'{average} result = 1.1')
    elif average == 60:
        print(f'{average} result = 1.0')
if command == 70:
    if average < 6:
        print(f'{average} result = 4.8')
    elif average == 7 or average == 8 or average == 9:
        print(f'{average} result = 4.7')
    elif average == 10 or average == 11:
        print(f'{average} result = 4.6')
    elif average == 12 or average == 13:
        print(f'{average} result = 4.5')
    elif average == 14 or average == 15:
        print(f'{average} result = 4.4')
    elif average == 16 or average == 17:
        print(f'{average} result = 4.3')
    elif average == 18 or average == 19:
        print(f'{average} result = 4.2')
    elif average == 20 or average == 21:
        print(f'{average} result = 4.1')
    elif average == 22 or average == 23:
        print(f'{average} result = 4.0')
    elif average == 24 or average == 25:
        print(f'{average} result = 3.9')
    elif average == 26 or average == 27:
        print(f'{average} result = 3.8')
    elif average == 28 or average == 29:
        print(f'{average} result = 3.7')
    elif average == 30 or average == 31:
        print(f'{average} result = 3.6')
    elif average == 32 or average == 33:
        print(f'{average} result = 3.5')
    elif average == 34 or average == 35:
        print(f'{average} result = 3.4')
    elif average == 36 or average == 37:
        print(f'{average} result = 3.3')
    elif average == 38 or average == 39:
        print(f'{average} result = 3.2')
    elif average == 40 or average == 41:
        print(f'{average} result = 3.1')
    elif average == 42:
        print(f'{average} result = 3.0')
    elif average == 43:
        print(f'{average} result = 2.9')
    elif average == 44:
        print(f'{average} result = 2.8')
    elif average == 45:
        print(f'{average} result = 2.7')
    elif average == 46:
        print(f'{average} result = 2.6')
    elif average == 47 or average == 48:
        print(f'{average} result = 2.5')
    elif average == 49 or average == 50:
        print(f'{average} result = 2.4')
    elif average == 51 or average == 52:
        print(f'{average} result = 2.3')
    elif average == 53 or average == 54:
        print(f'{average} result = 2.2')
    elif average == 55 or average == 56:
        print(f'{average} result = 2.1')
    elif average == 57 or average == 58:
        print(f'{average} result = 2.0')
    elif average == 59 or average == 60:
        print(f'{average} result = 1.9')
    elif average == 61 or average == 62:
        print(f'{average} result = 1.8')
    elif average == 63:
        print(f'{average} result = 1.7')
    elif average == 64:
        print(f'{average} result = 1.6')
    elif average == 65:
        print(f'{average} result = 1.5')
    elif average == 66:
        print(f'{average} result = 1.4')
    elif average == 67:
        print(f'{average} result = 1.3')
    elif average == 68:
        print(f'{average} result = 1.2')
    elif average == 69:
        print(f'{average} result = 1.1')
    elif average == 70:
        print(f'{average} result = 1.0')
if command == 80:
    if average == 1 or average == 2 or average == 3:
        print(f'{average} result = 4.9')
    elif average == 4 or average == 5 or average == 6:
        print(f'{average} result = 4.8')
    elif average == 7 or average == 8 or average == 9:
        print(f'{average} result = 4.7')
    elif average == 10 or average == 12:
        print(f'{average} result = 4.6')
    elif average == 13 or average == 14 or average == 15:
        print(f'{average} result = 4.5')
    elif average == 16 or average == 17 or average == 18:
        print(f'{average} result = 4.4')
    elif average == 19 or average == 20 or average == 21:
        print(f'{average} result = 4.3')
    elif average == 22 or average == 23 or average == 24:
        print(f'{average} result = 4.2')
    elif average == 25 or average == 26 or average == 27:
        print(f'{average} result = 4.1')
    elif average == 28 or average == 29:
        print(f'{average} result = 4.0')
    elif average == 30 or average == 31:
        print(f'{average} result = 3.9')
    elif average == 32 or average == 33:
        print(f'{average} result = 3.8')
    elif average == 34 or average == 35:
        print(f'{average} result = 3.7')
    elif average == 36 or average == 37:
        print(f'{average} result = 3.6')
    elif average == 38 or average == 39:
        print(f'{average} result = 3.5')
    elif average == 40 or average == 41:
        print(f'{average} result = 3.4')
    elif average == 42 or average == 43:
        print(f'{average} result = 3.3')
    elif average == 44 or average == 45:
        print(f'{average} result = 3.2')
    elif average == 46 or average == 47:
        print(f'{average} result = 3.1')
    elif average == 48:
        print(f'{average} result = 3.0')
    elif average == 49:
        print(f'{average} result = 2.9')
    elif average == 50:
        print(f'{average} result = 2.8')
    elif average == 51 or average == 52:
        print(f'{average} result = 2.7')
    elif average == 53 or average == 54:
        print(f'{average} result = 2.6')
    elif average == 55 or average == 56:
        print(f'{average} result = 2.5')
    elif average == 57 or average == 58:
        print(f'{average} result = 2.4')
    elif average == 59 or average == 60:
        print(f'{average} result = 2.3')
    elif average == 61 or average == 62:
        print(f'{average} result = 2.2')
    elif average == 63 or average == 64:
        print(f'{average} result = 2.1')
    elif average == 65 or average == 66:
        print(f'{average} result = 2.0')
    elif average == 67 or average == 68:
        print(f'{average} result = 1.9')
    elif average == 69 or average == 70:
        print(f'{average} result = 1.8')
    elif average == 71 or average == 72:
        print(f'{average} result = 1.7')
    elif average == 73 or average == 74:
        print(f'{average} result = 1.6')
    elif average == 75:
        print(f'{average} result = 1.5')
    elif average == 76:
        print(f'{average} result = 1.4')
    elif average == 77:
        print(f'{average} result = 1.3')
    elif average == 78:
        print(f'{average} result = 1.2')
    elif average == 79:
        print(f'{average} result = 1.1')
    elif average == 80:
        print(f'{average} result = 1.0')
if command == 90:
    if average >= 1 and not average >= 5:
        print(f'{average} result = 4.9')
    elif average >= 5 and not average == 9:
        print(f'{average} result = 4.8')
    elif average >= 9 and not average == 12:
        print(f'{average} result = 4.7')
    elif average >= 12 and not average == 15:
        print(f'{average} result = 4.6')
    elif average >= 15 and not average == 18:
        print(f'{average} result = 4.5')
    elif average >= 18 and not average == 21:
        print(f'{average} result = 4.4')
    elif average >= 21 and not average == 24:
        print(f'{average} result = 4.3')
    elif average >= 24 and not average == 27:
        print(f'{average} result = 4.2')
    elif average >= 27 and not average == 30:
        print(f'{average} result = 4.1')
    elif average >= 30 and not average == 33:
        print(f'{average} result = 4.0')
    elif average >= 33 and not average == 36:
        print(f'{average} result = 3.9')
    elif average >= 36 and not average == 39:
        print(f'{average} result = 3.8')
    elif average >= 39 and not average == 42:
        print(f'{average} result = 3.7')
    elif average >= 42 and not average == 44:
        print(f'{average} result = 3.6')
    elif average >= 44 and not average == 46:
        print(f'{average} result = 3.5')
    elif average >= 46 and not average == 48:
        print(f'{average} result = 3.4')
    elif average >= 48 and not average == 50:
        print(f'{average} result = 3.3')
    elif average == 50 or average == 51:
        print(f'{average} result = 3.2')
    elif average == 52 or average == 53:
        print(f'{average} result = 3.1')
    elif average == 54:
        print(f'{average} result = 3.0')
    elif average == 55:
        print(f'{average} result = 2.9')
    elif average == 56:
        print(f'{average} result = 2.8')
    elif average == 57:
        print(f'{average} result = 2.7')
    elif average == 58 or average == 59:
        print(f'{average} result = 2.6')
    elif average == 60 or average == 61:
        print(f'{average} result = 2.5')
    elif average == 62 or average == 63:
        print(f'{average} result = 2.4')
    elif average == 64 or average == 65:
        print(f'{average} result = 2.3')
    elif average == 66 or average == 67:
        print(f'{average} result = 2.2')
    elif average == 68 or average == 69:
        print(f'{average} result = 2.1')
    elif average == 70 or average == 71:
        print(f'{average} result = 2.0')
    elif average == 72 or average == 73:
        print(f'{average} result = 1.9')
    elif average == 74 or average == 75:
        print(f'{average} result = 1.8')
    elif average == 76 or average == 77:
        print(f'{average} result = 1.7')
    elif average == 78 or average == 79:
        print(f'{average} result = 1.6')
    elif average == 80 or average == 81:
        print(f'{average} result = 1.5')
    elif average == 82 or average == 83:
        print(f'{average} result = 1.4')
    elif average == 84 or average == 85:
        print(f'{average} result = 1.3')
    elif average == 86 or average == 87:
        print(f'{average} result = 1.2')
    elif average == 88 or average == 89:
        print(f'{average} result = 1.1')
    elif average == 90:
        print(f'{average} result = 1.0')
if command == 100:
    if average == 1:
        print(f'{average} result = 4.9')
    elif average == 5 or average == 6 or average == 7 or average == 8:
        print(f"{average} result = 4.8")
    elif average == 9 or average == 10 or average == 11 or average == 12:
        print(f'{average} result = 4.7')
    elif average == 13 or average == 15 or average == 16:
        print(f'{average} result = 4.6')
    elif average == 17 or average == 18 or average == 19 or average == 20:
        print(f'{average} result = 4.5')
    elif average == 21 or average == 22 or average == 23 or average == 24:
        print(f'{average} result = 4.4')
    elif average == 25 or average == 26 or average == 27 or average == 28:
        print(f'{average} result = 4.3')
    elif average == 29 or average == 30 or average == 31:
        print(f'{average} result = 4.2')
    elif average == 32 or average == 33 or average == 34:
        print(f'{average} result = 4.1')
    elif average == 35 or average == 36 or average == 37:
        print(f'{average} result = 4.0')
    elif average == 38 or average == 39 or average == 40:
        print(f'{average} result = 3.9')
    elif average == 41 or average == 42 or average == 43:
        print(f'{average} result = 3.8')
    elif average == 44 or average == 45 or average == 46:
        print(f'{average} result = 3.7')
    elif average == 47 or average == 48 or average == 49:
        print(f'{average} result = 3.6')
    elif average == 50 or average == 51:
        print(f'{average} result = 3.5')
    elif average == 52 or average == 53:
        print(f'{average} result = 3.4')
    elif average == 54 or average == 55:
        print(f'{average} result = 3.3')
    elif average == 56 or average == 57:
        print(f'{average} result = 3.2')
    elif average == 58 or average == 59:
        print(f'{average} result = 3.1')
    elif average == 60 or average == 61:
        print(f'{average} result = 3.0')
    elif average == 62 or average == 63:
        print(f'{average} result = 2.9')
    elif average == 64 or average == 65:
        print(f'{average} result = 2.8')
    elif average == 66 or average == 67:
        print(f'{average} result = 2.7')
    elif average == 68 or average == 69:
        print(f'{average} result = 2.6')
    elif average == 70 or average == 71:
        print(f'{average} result = 2.5')
    elif average == 72 or average == 73:
        print(f'{average} result = 2.4')
    elif average == 74 or average == 75:
        print(f'{average} result = 2.3')
    elif average == 76 or average == 77:
        print(f'{average} result = 2.2')
    elif average == 78 or average == 79:
        print(f'{average} result = 2.1')
    elif average == 80 or average == 81:
        print(f'{average} result = 2.0')
    elif average == 82 or average == 83:
        print(f'{average} result = 1.9')
    elif average == 84 or average == 85:
        print(f'{average} result = 1.8')
    elif average == 86 or average == 87:
        print(f'{average} result = 1.7')
    elif average == 88 or average == 89:
        print(f'{average} result = 1.6')
    elif average == 90 or average == 91:
        print(f'{average} result = 1.5')
    elif average == 92 or average == 93:
        print(f'{average} result = 1.4')
    elif average == 94 or average == 95:
        print(f'{average} result = 1.3')
    elif average == 96 or average == 97:
        print(f'{average} result = 1.2')
    elif average == 98 or average == 99:
        print(f'{average} result = 1.1')
    elif average == 100:
        print(f'{average} result = 1.0')
else:
    print("invalid transmutaion")
    print("please try again")
